### ISSUE TITLE
MVC samples are broken. DependencyModel throws exception.

### ISSUE THREAD

**Issue by troydai** [aspnet/cli-samples#24]
```
$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001780)

Product Information:
 Version:     1.0.0-beta-001780
 Commit Sha:  2ce679c57d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.11102
 OS Platform: Windows
 Runtime Id:  win10-x64
```

```
C:\code\cli-samples\HelloMvc [troy/db] [1.0.0.001765]
$ dotnet run
Project HelloMvc (.NETStandardApp,Version=v1.3) was previously compiled. Skipping compilation.
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
Hosting environment: Production
Content root path: C:\code\cli-samples\HelloMvc
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HKQD2RN8KGRF" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HKQD2RN8KGRE" started.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path / does not match a supported file type
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JObject root)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
  at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultAssemblyProvider..ctor(IApplicationEnvironment environment)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 352.0816ms 200
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HKQD2RN8KGRF" completed keep alive response.
```

**Comment by troydai** [comment]
Update: the `Microsoft.Extensions.DependencyModel` is 1.0.0-beta-001584. It is old. The sample is restored against __aspnetcidev__ which hasn't taken the latest dotnet-cli packages yet.

**Comment by troydai** [comment]
This could be a conflict between the latest `dotnet-cli` and the old `DependencyModel` package used by MVC.

**Comment by nmschulte** [comment]
@troydai, I just created PR #25 before looking at your issue.  Given what I'm seeing here (what you said about `aspnetcidev`'s NuGet package feed), I'm wondering if our issues are related, or at the least that perhaps my PR is "mis-guided" in that the `aspnetcidev` feed is mean to encompass the `dotnet-core` feed, for the purposes of development.

**Comment by moozzyk** [comment]
I guess that once we have a coherence signed build things will be working again from the cidev. Until then I suggest using the volatile feed. We can't add other feeds as they bring newer versions of the packages and since we use * dependencies this will cause issues.

**Comment by troydai** [comment]
@nmschulte rollback the dotnet to 1.0.0-beta-001716 to get MVC sample work before MVC take in the latest `DependencyModel` project.

**Comment by pranavkm** [comment]
We've addressed the issue as part of https://github.com/aspnet/Mvc/commit/4299a4d50bd782b9253c0e69a0505463492bfc5f. In general, the build of the CLI that we've compiled and tested against is specified in https://github.com/aspnet/KoreBuild/blob/dev/build/cli.version.win. Using a version of the CLI that is newer than that might result in incompatibilities.
