### ISSUE TITLE
Fail to `dotnet restore` on osx 10-11

### ISSUE THREAD

**Issue by ojosdegris** [aspnet/cli-samples#9]
Is it supposed to run on osx 10.11 right now? 

```
> dotnet restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231
...
System.ArgumentException: More than one runtime.json file has declared imports for 'osx.10.11-x64'
Parameter name: runtimeName
   at Microsoft.Dnx.Tooling.RestoreCommand.FindRuntimeDependencies(String runtimeName, List`1 runtimeFiles, Dictionary`2 effectiveRuntimeSpecs, HashSet`1 allRuntimeNames, Func`2 circularImport)
   at Microsoft.Dnx.Tooling.RestoreCommand.FindRuntimeDependencies(String runtimeName, List`1 runtimeFiles, Dictionary`2 effectiveRuntimeSpecs, HashSet`1 allRuntimeNames)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
More than one runtime.json file has declared imports for 'osx.10.11-x64'
Parameter name: runtimeName

NuGet Config files used:
    /Users/vittore/projects/dotnet/cli-samples/nuget.config

Feeds used:
    https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/
    https://api.nuget.org/v3-flatcontainer/
    https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/
    https://www.myget.org/F/dotnet-cli/api/v3/flatcontainer/
```

**Comment by ojosdegris** [comment]
Worked after downloading and installing latest package.

**Comment by ojosdegris** [comment]
You can close it, thanks
